#! /bin/csh -f
set INCLUDE = /home/studinf/mklimko/Repozytoria/jprog/16_stack/cslib-wb
set CSLIB = $INCLUDE/cslib.a
set LIBRARIES = ($CSLIB -lm)
foreach x ($*)
  if ("x$x" == "x-c") then
    set LIBRARIES = ""
    break
  endif
end
gcc -g -I$INCLUDE $* $LIBRARIES
